### ISSUE TITLE
Incorrect debuff swap

### ISSUE THREAD

**Issue by Kunaiswarm** [DimKaz/P12S-Pangenesis-mini-sim#1]
Unfortunately I was unable to reproduce the error but my friends pointed out to me that on occasion, long SE1 dark debuff will give another dark debuff but will want you to switch to dark tower and considers staying in light tower incorrect.

**Comment by DimKaz** [comment]
That's what I get for being the west most player and not testing the east as much. Swapped the color of the debuff.
When given a color debuff after NW1, SW1, NE1, SE1 it should always result in a swap so the tower was correct but I was indicating it with the wrong color.
